%language "c++"
%locations
%define api.prefix {igo}

%token TOKEN_BREAK TOKEN_CASE TOKEN_CHAN TOKEN_CONST TOKEN_CONTINUE
%token TOKEN_DEFAULT TOKEN_DEFER TOKEN_ELSE TOKEN_FALLTHROUGH
%token TOKEN_FOR TOKEN_FUNC TOKEN_GO TOKEN_GOTO TOKEN_IF
%token TOKEN_IMPORT TOKEN_INTERFACE TOKEN_MAP TOKEN_PACKAGE
%token TOKEN_RANGE TOKEN_RETURN TOKEN_SELECT TOKEN_STRUCT
%token TOKEN_SWITCH TOKEN_TYPE TOKEN_VAR

%%

top_level_decl: /* empty */
    | TOKEN_BREAK
;

%%
